{
  "openapi": "3.0.3",
  "info": {
    "title": "Santiago - OpenAPI 3.0",
    "description": "OpenAPI for Fake Shop Santiago - Practice using OpenAPI and Swagger in a fictional e-commerce context with simulated products and categories.",
    "contact": {
      "email": "msantiago0893@gmail.com"
    },
    "license": {
      "name": "Fake shop v1.0"
    },
    "version": "1.0.11"
  },
  "servers": [
    {
      "url": "https://api.escuelajs.co/api/v1"
    }
  ],
  "tags": [
    {
      "name": "category",
      "description": "Categories Service"
    },
    {
      "name": "store",
      "description": "Access to Petstore orders"
    },
    {
      "name": "user",
      "description": "Operations about user"
    },
    {
      "name": "product",
      "description": "Product Service"
    }
  ],
  "paths": {
    "/categories": {
      "get": {
        "tags": [
          "category"
        ],
        "summary": "Obtener categorías",
        "responses": {
          "200": {
            "description": "Respuesta exitosa",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "name": "Clothes",
                    "image": "https://i.imgur.com/x0K3SKA.jpeg",
                    "creationAt": "2023-10-06T18:41:34.000Z",
                    "updatedAt": "2023-10-06T18:41:34.000Z"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "category"
        ],
        "summary": "Agregar categoría",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "image": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "image"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Categoría agregada exitosamente"
          },
          "400": {
            "description": "Solicitud incorrecta"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      }
    },
    "/categories/{id}": {
      "get": {
        "tags": [
          "category"
        ],
        "summary": "Obtener categoría por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID de la categoría que se desea obtener",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Respuesta exitosa",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "name": "Clothes",
                  "image": "https://i.imgur.com/x0K3SKA.jpeg",
                  "creationAt": "2023-10-06T18:41:34.000Z",
                  "updatedAt": "2023-10-06T18:41:34.000Z"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "category"
        ],
        "summary": "Actualizar categoría",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID de la categoría que se desea actualizar",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  },
                  "image": {
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "name",
                  "image"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Categoría actualizada exitosamente"
          },
          "400": {
            "description": "Solicitud incorrecta"
          },
          "404": {
            "description": "Categoría no encontrada"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      },
      "delete": {
        "tags": [
          "category"
        ],
        "summary": "Eliminar categoría por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID de la categoría que se desea eliminar",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Categoría eliminada exitosamente"
          },
          "404": {
            "description": "Categoría no encontrada"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Consultar usuarios",
        "responses": {
          "200": {
            "description": "Respuesta exitosa",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "email": "john@mail.com",
                    "password": "changeme",
                    "name": "Jhon",
                    "role": "customer",
                    "avatar": "https://api.lorem.space/image/face?w=640&h=480&r=867"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Crear usuario",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "avatar": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "email",
                  "password"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Usuario creado exitosamente"
          },
          "400": {
            "description": "Solicitud incorrecta"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Consultar usuario por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID del usuario que se desea consultar",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Respuesta exitosa",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "email": "john@mail.com",
                  "password": "changeme",
                  "name": "Jhon",
                  "role": "customer",
                  "avatar": "https://api.lorem.space/image/face?w=640&h=480&r=867"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "user"
        ],
        "summary": "Actualizar usuario por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID del usuario que se desea actualizar",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string"
                  },
                  "avatar": {
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "email",
                  "password",
                  "name",
                  "role",
                  "avatar"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Usuario actualizado exitosamente"
          },
          "400": {
            "description": "Solicitud incorrecta"
          },
          "404": {
            "description": "Usuario no encontrado"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      },
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Eliminar usuario por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID del usuario que se desea eliminar",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Usuario eliminado exitosamente"
          },
          "404": {
            "description": "Usuario no encontrado"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      }
    },
    "/users/is-available": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Verificar si un email existe",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  }
                },
                "required": [
                  "email"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Respuesta exitosa",
            "content": {
              "application/json": {
                "example": {
                  "available": true
                }
              }
            }
          },
          "400": {
            "description": "Solicitud incorrecta"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      }
    },
    "/products": {
      "get": {
        "tags": [
          "product"
        ],
        "summary": "Consultar productos",
        "parameters": [
          {
            "name": "offset",
            "in": "query",
            "description": "Número de elementos a omitir desde el principio de la lista.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Número máximo de elementos a devolver.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "name",
            "in": "query",
            "description": "Título del producto para filtrar.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "price",
            "in": "query",
            "description": "Precio del producto para filtrar.",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "price min",
            "in": "query",
            "description": "Precio mínimo para el rango de precios.",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "price max",
            "in": "query",
            "description": "Precio máximo para el rango de precios.",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "category",
            "in": "query",
            "description": "ID de la categoría para filtrar productos.",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Respuesta exitosa",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 4,
                    "title": "Handmade Fresh Table",
                    "price": 687,
                    "description": "Andy shoes are designed to keeping in...",
                    "category": {
                      "id": 5,
                      "name": "Others",
                      "image": "https://placeimg.com/640/480/any?r=0.591926261873231"
                    },
                    "images": [
                      "https://placeimg.com/640/480/any?r=0.9178516507833767",
                      "https://placeimg.com/640/480/any?r=0.9300320592588625",
                      "https://placeimg.com/640/480/any?r=0.8807778235430017"
                    ]
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Solicitud incorrecta"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      },
      "post": {
        "tags": [
          "product"
        ],
        "summary": "Agregar producto",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "price": {
                    "type": "number"
                  },
                  "description": {
                    "type": "string"
                  },
                  "categoryId": {
                    "type": "integer"
                  },
                  "images": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": [
                  "title",
                  "price",
                  "description",
                  "categoryId",
                  "images"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Producto agregado exitosamente"
          },
          "400": {
            "description": "Solicitud incorrecta"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "tags": [
          "product"
        ],
        "summary": "Consultar producto por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID del producto que se desea consultar",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Respuesta exitosa",
            "content": {
              "application/json": {
                "example": {
                  "id": 4,
                  "title": "Handmade Fresh Table",
                  "price": 687,
                  "description": "Andy shoes are designed to keeping in...",
                  "category": {
                    "id": 5,
                    "name": "Others",
                    "image": "https://placeimg.com/640/480/any?r=0.591926261873231"
                  },
                  "images": [
                    "https://placeimg.com/640/480/any?r=0.9178516507833767",
                    "https://placeimg.com/640/480/any?r=0.9300320592588625",
                    "https://placeimg.com/640/480/any?r=0.8807778235430017"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Solicitud incorrecta"
          },
          "404": {
            "description": "Producto no encontrado"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      },
      "put": {
        "tags": [
          "product"
        ],
        "summary": "Actualizar producto por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID del producto que se desea actualizar",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "price": {
                    "type": "number"
                  },
                  "description": {
                    "type": "string"
                  },
                  "categoryId": {
                    "type": "integer"
                  },
                  "images": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": [
                  "title",
                  "price",
                  "description",
                  "categoryId",
                  "images"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Producto actualizado exitosamente"
          },
          "400": {
            "description": "Solicitud incorrecta"
          },
          "404": {
            "description": "Producto no encontrado"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      },
      "delete": {
        "tags": [
          "product"
        ],
        "summary": "Eliminar producto por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID del producto que se desea eliminar",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Producto eliminado exitosamente"
          },
          "404": {
            "description": "Producto no encontrado"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "image": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "avatar": {
            "type": "string"
          }
        }
      },
      "Product": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string"
          },
          "price": {
            "type": "number"
          },
          "description": {
            "type": "string"
          },
          "category": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "image": {
                "type": "string"
              }
            }
          },
          "images": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}